version: '3.5'
services:
    app:
        container_name: store-management
        build:
            context: ../../
            dockerfile: build/Dockerfile
        volumes:
            - ../../:/src/go
        working_dir: /src/go/cmd/hash
        ports:
            - 8080:8080
        command: reflex -r '(\.go$$)' -s go run .

